jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Template
        uses: actions/checkout@v4 # Updated version

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env:
          CI: false # This prevents warnings from failing the build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ # or ./build/ depending on your config
